# https://book.getfoundry.sh/reference/config/overview

[profile.default]
src = "contracts"
remappings = [
	'@unruggable/=node_modules/@unruggable/',
	'@ensdomains/=node_modules/@ensdomains/'
]
libs = ["node_modules", "lib"]
